### ISSUE TITLE
feat : 포스팅 댓글 UI 개발 

### ISSUE THREAD

**Issue by SUPINKIM** [T28-Blog/blog-front#12]
![기본](https://user-images.githubusercontent.com/49034615/121485153-e2e3dd80-ca0a-11eb-8ebb-7f2f03d01b35.png)
![max-width : 768px](https://user-images.githubusercontent.com/49034615/121485166-e5dece00-ca0a-11eb-9e80-554fd374deac.png)
![max-width : 375px](https://user-images.githubusercontent.com/49034615/121485172-e70ffb00-ca0a-11eb-8c13-beea2fddb247.gif)

 - 댓글 노출 최대 3줄, 화면 크기에 따라 3줄 이상이 넘어가는 경우 더보기 버튼 노출
 - components/Comments.js : 전체 댓글 UI 개발 / components/CommentText.js : 댓글 별로 resizing을 위해 별도 컴포넌트 생성
 - hooks/useResizeObserver.js : 화면 사이즈 변경에 따른 반응형 UI 구현을 위한 커스텀 Hooks
 - mock.js : 추후 api 생성 시 삭제
 - 댓글 생성 기능의 경우, 이후 api 개발 이후 테스트 예정

+ Read.me 파일 작성 중

**Comment by hurima90-kim** [comment]
@SUPINKIM 회원가입시에 따로 프로필이미지를 등록하지 않는데, 댓글부분에서 사용자프로필이미지가 필요한 부분일까요??
그리고 내가 작성한 댓글에 한해서 수정 / 삭제 버튼이 필요할 것 같아요

**Comment by hurima90-kim** [comment]
@SUPINKIM @SUPINKIM 대댓글은 어떤식으로 동작이 되는지에 대한 이야기가 필요할 듯 하네요
'@ userid' 와 같이 태그방식으로 작성을 할지? 아니면 해당 댓글에 마우스오버나 클릭시 댓글작성란이 노출될지 등등

**Comment by SUPINKIM** [comment]
회원 가입 시에는 프로필 사진 안 받고 보통 마이 페이지에서 프로필 사진 수정하니까 그냥 둬도 괜찮을 것 같아요. (기본 프로필 사진 default 이미지로 설정해두면 될 것 같습니다.)
대댓글은 아직 구현하지 않아서 오늘 회의에서 의견 주시면 반영해서 작업해보도록 할게요. 
내가 작성한 댓글에 한해서 수정/삭제 버튼도 추가하겠습니다. 
레이아웃 잡는 건 문제가 아닌데 결국 말씀 주신 기능 포함 댓글 생성하는 게 로그인 기능이 완료 되지 않으면 레이아웃 잡는 수준밖에 안 돼서 
일단 이번주, 다음주 초 내로 로그인 먼저 끝내는 방향으로 진행하는 걸 제안드립니다!
