### ISSUE TITLE
404 에러페이지 확인

### ISSUE THREAD

**Issue by hurima90-kim** [T28-Blog/blog-front#21]
## 작업사항
- 잘못된 주소를 입력했을 시 나타나는 404에러페이지 구현
- PC, Mobile, Tablet 3가지의 반응형 레이아웃 구현

## 요청사항
추가적으로 필요한 사항이나 수정이 필요한 부분에 대한 의견필요

## 스크린샷
![image](https://user-images.githubusercontent.com/66353903/121778780-7bc55500-cbd3-11eb-9e35-ea22a3192ba0.png)

**Comment by SUPINKIM** [comment]
와우ㅎ 너무 좋은데요? 너무 좋다는 말 밖엔 드릴 말씀이 없네요 쌍따봉 드립니다. 👍👍

**Comment by yjclarelee** [comment]
너무 귀여워요! 좋습니다
