### ISSUE TITLE
feat : kakao 로그인 기능 구현 및 로그인 여부에 따른 header 영역 변경 구현

### ISSUE THREAD

**Issue by SUPINKIM** [T28-Blog/blog-front#4]
![Kapture 2021-06-02 at 15 44 12](https://user-images.githubusercontent.com/49034615/120436117-7ee16980-c3b9-11eb-8894-5d3d96931536.gif)

**Comment by hurima90-kim** [comment]
카카오, 구글, 네이버 로그인 모두 팝업(모달창) 형태로 띄워서 로그인을 진행하면 어떨까요? 
소셜로그인 기능을 제공하는 각 회사들마다 해당페이지 레이아웃이 다 달라서 디자인 부분이 틀어지는 것 같아요

**Comment by SUPINKIM** [comment]
네이버 로그인의 경우 팝업 형태로 진행하셨나요? 카카오의 경우, 팝업 형태로 띄우려면 rest api가 아닌 javascript sdk를 활용해야 하는 것으로 알고 있는데요, 저희 프로젝트의 경우 sdk 사용이 알맞지 않은 것 같아서 sdk로 진행하려면 서치가 좀 더 필요할 것 같습니다.

**Comment by hurima90-kim** [comment]
@SUPINKIM 말씀하신 부분 저도 같이 한번 찾아볼께요. 네이버 로그인에 관한 사항은 회의때 다시 말씀드릴께요
